//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MasterDetails_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Exprience
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Disignation { get; set; }
        public int YearOfExprience { get; set; }
        public int ApplicantId { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
